# Generated by Django 3.1.4 on 2020-12-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_slider_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='button_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
