# Generated by Django 3.1.4 on 2020-12-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_slider_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='button_url',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
