# Generated by Django 3.1.4 on 2020-12-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_auto_20201216_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='youtube_link',
            field=models.URLField(blank=True, default='youtube.com', max_length=250),
        ),
    ]
