# Generated by Django 3.1.4 on 2020-12-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_teammember_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='youtube_link',
            field=models.URLField(blank=True, default='http://youtube.com', max_length=250),
        ),
    ]
