# Generated by Django 3.1.4 on 2020-12-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0011_aboutmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
