# Generated by Django 3.1.4 on 2020-12-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0014_auto_20201228_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
