# Generated by Django 3.1.4 on 2020-12-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtuber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('categorey', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('age', models.IntegerField(max_length=200)),
                ('height', models.IntegerField(max_length=200, verbose_name='heigth(cm)')),
                ('team', models.CharField(max_length=200, verbose_name='Team Type')),
                ('camera', models.CharField(max_length=200, verbose_name='Camera Type')),
                ('subscriber_count', models.CharField(max_length=200, verbose_name='Subscriber Count')),
                ('price', models.IntegerField(verbose_name='Base Price')),
                ('youtube_link', models.URLField(default='https://youtube.com')),
                ('image', models.ImageField(upload_to='media/youtubers/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
