# Generated by Django 3.1.4 on 2020-12-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuber',
            name='display_vedio_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='youtuber',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='height',
            field=models.IntegerField(verbose_name='heigth(cm)'),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='image',
            field=models.ImageField(upload_to='media/youtubers/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='youtube_link',
            field=models.URLField(default='https://youtube.com', verbose_name='Youtube Channel Link'),
        ),
    ]
