# Generated by Django 3.1.4 on 2020-12-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0003_auto_20201217_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ytuber',
            name='height',
        ),
        migrations.AddField(
            model_name='ytuber',
            name='youtube_channel_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
