# Generated by Django 3.1.4 on 2020-12-17 17:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0004_auto_20201217_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytuber',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='ytuber',
            name='image',
            field=models.ImageField(upload_to='media/youtubers/%Y/%m', verbose_name='dp image'),
        ),
    ]
