# Generated by Django 3.1.4 on 2020-12-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0005_auto_20201217_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytuber',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Dp URL'),
        ),
        migrations.AlterField(
            model_name='ytuber',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/youtubers/%Y/%m', verbose_name='dp image (dp image or dp Url)'),
        ),
    ]
