# Generated by Django 3.1.4 on 2020-12-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0006_auto_20201218_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytuber',
            name='categorey',
            field=models.CharField(choices=[('cooking', 'cooking'), ('lifestyle', 'lifestyle'), ('comedy', 'comedy'), ('tech', 'tech'), ('music', 'music'), ('kids', 'kids'), ('gaming', 'gaming'), ('travel', 'travel'), ('others', 'others')], max_length=200),
        ),
        migrations.AlterField(
            model_name='ytuber',
            name='team_type',
            field=models.CharField(choices=[('solo', 'solo'), ('small ', 'small '), ('large ', 'large ')], max_length=200),
        ),
    ]
