# Generated by Django 3.1.4 on 2020-12-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0007_auto_20201219_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytuber',
            name='email',
            field=models.EmailField(default='8921test@gmail.com', max_length=254),
        ),
    ]
