# Generated by Django 3.1.4 on 2020-12-28 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0009_contacttuber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactTuber',
        ),
    ]
