# Generated by Django 3.1.4 on 2020-12-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0011_contactmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactModel',
        ),
    ]
