# Generated by Django 3.1.4 on 2020-12-27 05:51

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('youtubers', '0009_contacttuber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=400)),
                ('date_contacted', models.DateTimeField(auto_now_add=True)),
                ('ytuber_contacted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtubers.ytuber')),
            ],
        ),
    ]
