# Generated by Django 3.1.4 on 2020-12-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_tuber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
